version: '3.3'

# https://github.com/jonashackt/cxf-spring-cloud-netflix-docker/tree/buildpacks-paketo

services:
  eureka-service:
    restart: unless-stopped
    image: eureka:0.0.1-SNAPSHOT
    ports:
      - '8761:8761'
    networks:
      - spring-cloud-network
  gateway-service:
    restart: unless-stopped
    image: gateway:0.0.1-SNAPSHOT
    ports:
      - '8080:8080'
    networks:
      - spring-cloud-network
    depends_on:
      - eureka-service
  user-service:
    restart: unless-stopped
    image: user-service:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    networks:
      - spring-cloud-network
    depends_on:
      - eureka-service
      - gateway-service
  posts-service:
    restart: unless-stopped
    image: posts-service:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    networks:
      - spring-cloud-network
    depends_on:
      - eureka-service
      - gateway-service
networks:
  spring-cloud-network:
    driver: bridge