server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    refresh:
      enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-service:8761/eureka} # Link to eureka-service container

jwt:
  secret: screte-value

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info