spring:
  application:
    name: posts-service
  cloud:
    refresh:
      enabled: false
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-service:8761/eureka}
  instance:
    preferIpAddress: true